# Generated by Django 4.0.4 on 2022-04-28 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_rename_anything_topic_poshel_nafig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='poshel_nafig',
            new_name='text',
        ),
    ]
